config/routes.rb
LidiaKozokin::Application.routes.draw do
  resources :photos

  resources :messages

  get "main/index"

  resources :general_texts

  root :to => 'main#index'

end

app/models/general_text.rb
class GeneralText < ActiveRecord::Base
  attr_accessible :text_name, :text_value

  validates :text_name, presence: true , uniqueness: true
  validates :text_value, length: { maximum: 1000,
    too_long: "%{count} characters is the maximum allowed" }

 def self.hash
  h={}
  self.all.each {|c| h[c.text_name.to_sym]=c.text_value.to_s}
  h
 end

end

app/models/image_type.rb
class ImageType < ActiveRecord::Base
  attr_accessible :name

  has_one :photo
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :image_src, :image_type_id, :name, :thumb_src

  validates :name , :image_type_id, :thumb_src ,:image_src , presence: true

  belongs_to :image_type

  def css_class
  	self.image_type.name.sub(' ' , '_').downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/general_texts_controller.rb
class GeneralTextsController < ApplicationController
  # GET /general_texts
  # GET /general_texts.json
  layout 'admin'

  def index
    @general_texts = GeneralText.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @general_texts }
    end
  end

  # GET /general_texts/1
  # GET /general_texts/1.json
  def show
    @general_text = GeneralText.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @general_text }
    end
  end

  # GET /general_texts/new
  # GET /general_texts/new.json
  def new
    @general_text = GeneralText.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @general_text }
    end
  end

  # GET /general_texts/1/edit
  def edit
    @general_text = GeneralText.find(params[:id])
  end

  # POST /general_texts
  # POST /general_texts.json
  def create
    @general_text = GeneralText.new(params[:general_text])

    respond_to do |format|
      if @general_text.save
        format.html { redirect_to @general_text, notice: 'General text was successfully created.' }
        format.json { render json: @general_text, status: :created, location: @general_text }
      else
        format.html { render action: "new" }
        format.json { render json: @general_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /general_texts/1
  # PUT /general_texts/1.json
  def update
    @general_text = GeneralText.find(params[:id])

    respond_to do |format|
      if @general_text.update_attributes(params[:general_text])
        format.html { redirect_to @general_text, notice: 'General text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @general_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /general_texts/1
  # DELETE /general_texts/1.json
  def destroy
    @general_text = GeneralText.find(params[:id])
    @general_text.destroy

    respond_to do |format|
      format.html { redirect_to general_texts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@texts = GeneralText.hash
  	@message = Message.new
  	@photos = Photo.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  layout 'admin'
  
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_texts_helper.rb
module GeneralTextsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/general_texts/_form.html.erb
<%= form_for(@general_text) do |f| %>
  <% if @general_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@general_text.errors.count, "error") %> prohibited this general_text from being saved:</h2>

      <ul>
      <% @general_text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text_name %><br />
    <%= f.text_field :text_name %>
  </div>
  <div class="field">
    <%= f.label :text_value %><br />
    <%= f.text_area :text_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/general_texts/edit.html.erb
<h1>Editing general_text</h1>

<%= render 'form' %>

<%= link_to 'Show', @general_text %> |
<%= link_to 'Back', general_texts_path %>

app/views/general_texts/index.html.erb
<h1>Listing general_texts</h1>

<table>
  <tr>
    <th>Text name</th>
    <th>Text value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @general_texts.each do |general_text| %>
  <tr>
    <td><%= general_text.text_name %></td>
    <td><%= general_text.text_value %></td>
    <td><%= link_to 'Show', general_text %></td>
    <td><%= link_to 'Edit', edit_general_text_path(general_text) %></td>
    <td><%= link_to 'Destroy', general_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New General text', new_general_text_path %>

app/views/general_texts/new.html.erb
<h1>New general_text</h1>

<%= render 'form' %>

<%= link_to 'Back', general_texts_path %>

app/views/general_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text name:</b>
  <%= @general_text.text_name %>
</p>

<p>
  <b>Text value:</b>
  <%= @general_text.text_value %>
</p>


<%= link_to 'Edit', edit_general_text_path(@general_text) %> |
<%= link_to 'Back', general_texts_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lidia Kozokin - Web Designer & Graphic Design</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "", '#', id: "logo" %>
          <nav class="nav pull-right">
            <ul class="nav pull-right">
              <li><%= link_to "Genral text", general_texts_path%></li>
              <li><%= link_to "Photos", photos_path %></li>
              <li><%= link_to "Back to website", root_url %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    
      <%= yield %>
    
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lidia Kozokin - Web Designer & Graphic Design</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "", '#', id: "logo" %>
          <nav class="nav pull-right">
            <ul class="nav pull-right">
              <li><%= link_to "home",    '#' %></li>
              <li><%= link_to "about",    '#' %></li>
              <li><%= link_to "portfolio",    '#' %></li>
              <li><%= link_to "contact", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    
      <%= yield %>
    
    
  </body>
</html>

app/views/main/_about.html.erb
<div id="about" class="about section">
	<div class="href-sperator"></div>
	<div class="container">
		<div class="grey-doll"></div>
		<h1>About</h1>
		<div class="hr"></div>
		<div class="span6">
			<h4><%= @texts[:about_bold].upcase %></h4>
			<div class="about-content"><%= @texts[:about_content] %></div>
			<div class="row">
				<div class="circle about-circle">Photoshop</div>
				<div class="circle about-circle">Illustrator</div>
				<div class="circle about-circle">Flash</div>
				<div class="circle about-circle">HTML/CSS</div>
			</div>
		</div>
		<div class="span4"><div class="about-photo"></div></div>

		
	</div>
</div>

app/views/main/_portfolio.html.erb
<div id="portfolio" class="portfolio section">
	<div class="href-sperator"></div>
	<div class="container">
		<h1>Portfolio</h1>
		<div class="hr"></div>
		<!--portfolio nav -->
		<div class="row" id="options">
			<div class="span2"><a href="#filter" data-filter="*"><div class="circle circle-portfolio circle-shadow">ALL</div></a></div>
			<div class="span2"><a href="#filter" data-filter=".flash_banners"><div class="circle circle-portfolio circle-shadow">FLASH BANNERS</div></a></div>
			<div class="span2"><a href="#filter" data-filter=".gif_banners"><div class="circle circle-portfolio circle-shadow">GIF BANNERS</div></a></div>
			<div class="span2"><a href="#filter" data-filter=".newlaters"><div class="circle circle-portfolio circle-shadow">NEWSLATERS</div></a></div>
			<div class="span2"><a href="#filter" data-filter=".websites"><div class="circle circle-portfolio circle-shadow">WEBSITES</div></a></div>
		</div>

<!-- start: Portfolio -->
	 <div class="span12 offset1">
  	
    	<section id="projects">
	    	<ul id="thumbs">
	        <% @photos.each do |photo| %>
						<!-- Item Project and Filter Name -->
        		<li class="item-thumbs span3 design <%= photo.image_type.name.sub(' ' , '_').downcase %>" >
                <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="<%= photo.name%>" href="<%= photo.image_src%>">
                    <span class="overlay-img"></span>
                    <span class="overlay-img-thumb font-icon-search"></span>
                </a>
                <!-- Thumb Image and Description -->
                <img src="<%= photo.image_src%>" alt="<%= photo.description%>">
            </li>
	        <% end %>
	        	<!-- End Item Project -->
	       </ul>
        </section>
      
  	
   </div>
  <!-- End Portfolio Projects -->

		
	</div>

</div>

app/views/main/index.html.erb
<div id="profile" class="profile">
	<div class="container">
		<div class="profile-container">
			<div class="cloud"></div>
			<div class="span2 big-doll"></div>
			<div class="span7">
				<h1><span>W</span>EB DESIGN</h1>
				<h2>Graphic <span>D</span>esign</h2>

				<div class="profile-title"><%= @texts[:profile_title] %></div>
				<ul class="unstyled">
					<li><%= @texts[:profile_content1] %></li>
					<li><%= @texts[:profile_content2] %></li>
					<li><%= @texts[:profile_content3] %></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<!-- Portfolio -->
<%= render 'portfolio' %>


<!-- About -->
<%= render 'about' %>

<!-- Contact us -->
<div id="contact" class="contact section">
	<div class="container">
		<h1>Contact Me</h1>
		<div class="hr"></div>
		<div class="row">
			<div class="span3">
				<div><%= @texts[:contact_description] %></div>
				<p>
					<div>Call me or message me:</div>
					<div class="green-label"><%= @texts[:contact_phone] %></div>
				</p>
				<p>
				<div>Email me:</div>
				<div class="green-label"><%= @texts[:contact_email] %></div>
			</p>



			</div>
			<div class="span8">
				<%= render 'messages/form'  %>
			</div>
			
		</div>
		<div class="footer">
				<span class="footer-doll"></span>
				<span><span class="footer-label">design by</span> Kozokin Lidia</span>

			</div>
	</div>


</div>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span3">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="span3">
    <div class="field">
      <%= f.label :message %>
      <%= f.text_area :message , rows: 10%>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.name %></td>
    <td><%= message.phone %></td>
    <td><%= message.email %></td>
    <td><%= message.message %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @message.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @message.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @message.email %>
</p>

<p>
  <b>Message:</b>
  <%= @message.message %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_type_id %><br />
    <%= select("photo", "image_type_id", ImageType.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Select one'}) %>
  </div>
  <div class="field">
    <%= f.label :thumb_src %><br />
    <%= f.text_field :thumb_src %>
  </div>
  <div class="field">
    <%= f.label :image_src %><br />
    <%= f.text_area :image_src %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image type</th>
    <th>Thumb src</th>
    <th>Image src</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.name %></td>
    <td><%= photo.image_type_id %></td>
    <td><%= photo.thumb_src %></td>
    <td><%= photo.image_src %></td>
    <td><%= photo.description %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>

<p>
  <b>Image type:</b>
  <%= @photo.image_type_id %>
</p>

<p>
  <b>Thumb src:</b>
  <%= @photo.thumb_src %>
</p>

<p>
  <b>Image src:</b>
  <%= @photo.image_src %>
</p>

<p>
  <b>Description:</b>
  <%= @photo.description %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>